### ISSUE TITLE
报错：zlib.error: Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by MC-dusk** [MC-dusk/QRCD_M#2]
下载某些歌词时报错：`zlib.error: Error -3 while decompressing data: incorrect header check`

例如：

```
#2: (125387966) 传奇 / 王菲 /
#3: (125497372) 传奇 / 王菲 /
```

**Comment by MC-dusk** [comment]
暂时判断为QQ音乐不返回某些VIP歌曲的歌词，~~无解~~。

暂时解决办法：如果使用QQ音乐PC客户端，加载歌曲后（试听也可）可以得到大部分VIP歌曲的qrc歌词，存储在对应的歌词缓存文件夹中。使用[其他工具](https://gitee.com/ying32/MakeLyric)可以解码使用。

**Comment by Ephemeralwanning** [comment]
> 暂时判断为QQ音乐不返回某些VIP歌曲的歌词，~无解~。
> 
> 暂时解决办法：如果使用QQ音乐PC客户端，加载歌曲后（试听也可）可以得到大部分VIP歌曲的qrc歌词，存储在对应的歌词缓存文件夹中。使用[其他工具](https://gitee.com/ying32/MakeLyric)可以解码使用。

可否加一个批量爬取歌单中歌词的功能

**Comment by MC-dusk** [comment]
> 

可使用这个：https://github.com/jitwxs/163MusicLyrics

**Comment by MC-dusk** [comment]
> 可否加一个批量爬取歌单中歌词的功能

@Ephemeralwanning 
可使用这个：https://github.com/jitwxs/163MusicLyrics

**Comment by Ephemeralwanning** [comment]
> > 可否加一个批量爬取歌单中歌词的功能
> 
> @Ephemeralwanning 可使用这个：https://github.com/jitwxs/163MusicLyrics

似乎也不能批量下载歌单歌词 得一个一个输入id

**Comment by MC-dusk** [comment]
> 似乎也不能批量下载歌单歌词 得一个一个输入id

v5.4加入了
