### ISSUE TITLE
使用最新的qrcd_m.exe遇到了一些问题

### ISSUE THREAD

**Issue by byddgithubzh** [MC-dusk/QRCD_M#4]
我下载了release中最新的qrcd_m.exe，程序能正常运行，输入歌曲名&歌手名也能搜索，但是在选择序号下载后产生了一个空文件夹，并没有lrc歌词文件，而且通过录屏我发现程序报错了。

![image](https://user-images.githubusercontent.com/78755339/201481566-2875361b-29ec-4175-ae5d-dbed7f72d92c.png)

尝试下载完整的仓库，将qrcd_m.exe移动到\QRCD_M-master\files中，程序却可以正常运行了。
![image](https://user-images.githubusercontent.com/78755339/201482013-42a62c4a-9ebc-44ac-8c29-64690e9b00f1.png)

是因为我缺少什么环境吗？

**Comment by MC-dusk** [comment]
我改一下release吧，当时偷懒传的不是压缩包，果然会误导吗...

> 热更新：下载qrcd_m.exe覆盖[v0.2](https://github.com/MC-dusk/QRCD_M/releases/download/v0.2/qrcd_m_v0.2.7z)对应文件即可

意思是先下载v0.2.0，再下载v0.2.1覆盖更新，单独一个exe不够。
